site_name: Material for Teobot
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: nauqh/teobot
theme:
    logo: assets/education.png
    favicon: assets/education.png
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
    language: en
    palette:
        accent: yellow

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/nauqh
        - icon: fontawesome/brands/discord
          link: https://discord.gg/DQ9QBM6HFW

nav:
    - Home: index.md
    - What's New: release.md
    - FAQ: faq.md

markdown_extensions:
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true

copyright: |
    Copyright &copy; 2024 <a href="https://github.com/nauqh"  target="_blank">Nauqh</a>
