site_name: Teobot
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: nauqh/teobot
theme:
    logo: assets/poro.png
    favicon: assets/poro.png
    name: material
    features:
        - navigation.tabs
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy
        - content.tooltips
    language: en
    palette:
        primary: blue grey
        accent: teal

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/nauqh
        - icon: fontawesome/brands/discord
          link: https://discord.gg/DQ9QBM6HFW

markdown_extensions:
    - abbr
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.tasklist:
          custom_checkbox: true
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
    Design & developed by <a href="https://github.com/nauqh"  target="_blank">Nauqh</a>
